### PR TITLE
Upgrade to v1.7.7 and add new evdev dependency

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Requesting merge: @Tobias-Fischer

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
Need to wait until the `evdev` package is propagated into the package list. This is the reason aarch64 fails.

**Comment by ehfd** [comment]
@conda-forge-admin, please restart ci

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please restart ci

**Comment by ehfd** [comment]
Everything is in order.

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by ehfd** [comment]
If everything looks good, you could merge this yourself. @Tobias-Fischer

**Pull request merged**
