### PR TITLE
Python 3.12 manual migration

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready for review/merge @conda-forge/pynput 

/cc @ehfd

**Comment by ehfd** [comment]
@Tobias-Fischer You should add yourself as a maintainer. Thank you so much.

@xhochy requesting review.

**Comment by xhochy** [comment]
Please tag core and not just me in thesw cases. 

I'm happy to merge if @Tobias-Fischer adds himself as maintainer. The maintainers here are also absent from other feedstocks.

**Comment by ehfd** [comment]
I forgot about tagging core after reading the manuals. Sorry.

**Comment by Tobias-Fischer** [comment]
Done @xhochy

**Pull request merged**
