### PR TITLE
Add osx-arm64+linux-aarch64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge/pynput - this is ready for review :)

**Comment by Tobias-Fischer** [comment]
This incorporates changes from #10 and #12 

/cc @xhochy

**Review by xhochy — APPROVED** [review]
Merging as feedstock seems abandonded.

**Comment by Tobias-Fischer** [comment]
Thank you @xhochy

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@Tobias-Fischer @xhochy Any particular reasons there might not be a Python 3.12 build?

**Comment by Tobias-Fischer** [comment]
Seems like it hasn’t been migrated yet - please check the conda forge migration page to see if all dependencies have been migrated.

**Comment by ehfd** [comment]
not solvable (
bot CI job
) @ main
                osx_arm64_python3.8.____cpython: Could not solve for environment specs
The following packages are incompatible
├─ pyobjc-framework-applicationservices is installable with the potential options
│  ├─ pyobjc-framework-applicationservices 10.1 would require
│  │  ├─ pyobjc-framework-quartz >=10.1  with the potential options
│  │  │  ├─ pyobjc-framework-quartz [10.0|10.1|...|9.2] would require
│  │  │  │  └─ python_abi 3.10.* *_cp310, which can be installed;
│  │  │  ├─ pyobjc-framework-quartz [10.0|10.1|...|9.2] would require
│  │  │  │  └─ python_abi 3.9.* *_cp39, which can be installed;
│  │  │  ├─ pyobjc-framework-quartz [10.0|10.1|...|9.2] would require
│  │  │  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  │  │  └─ pyobjc-framework-quartz [10.0|10.1|10.2|9.2] would require
│  │  │     └─ python_abi 3.12.* *_cp312, which can be installed;
│  │  └─ python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
│  ├─ pyobjc-framework-applicationservices 10.1 would require
│  │  └─ python_abi 3.10.* *_cp310, which can be installed;
│  ├─ pyobjc-framework-applicationservices 10.1 would require
│  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  ├─ pyobjc-framework-applicationservices 10.1 would require
│  │  └─ python_abi 3.12.* *_cp312, which can be installed;
│  └─ pyobjc-framework-applicationservices 10.1 would require
│     └─ python_abi 3.9.* *_cp39, which can be installed;
├─ pyobjc-framework-quartz, which can be installed (as previously explained);
├─ python >=3.8,<3.9.0a0  is not installable because it requires
│  └─ python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
└─ python_abi 3.8.* *_cp38 is not installable because it conflicts with any installable versions previously reported.

**Pull request merged**
